enableTelemetry: false

logFilters:
  - pattern: "@swc/core-*@npm:* The * architecture is incompatible with this module, link skipped."
    level: "discard"

nodeLinker: node-modules

packageExtensions:
  ts-standard@*:
    dependencies:
      "@typescript-eslint/parser": "^4.0.0"
  webpack-dev-server@*:
    dependencies:
      "@types/express": "^4.0.0"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
